# Generated by Django 3.0.8 on 2020-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('logTime', models.DateTimeField()),
                ('clickTime', models.DateTimeField()),
                ('currentPageId', models.IntegerField()),
                ('currentPageType', models.CharField(max_length=1)),
                ('userChoice', models.CharField(max_length=1)),
                ('date', models.CharField(max_length=8)),
                ('economy', models.IntegerField()),
                ('militancy', models.IntegerField()),
                ('consciousness', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('sinicization', models.IntegerField()),
            ],
            options={
                'unique_together': {('userId', 'logTime', 'clickTime')},
            },
        ),
    ]
